version: '3.9'

services:
  web:
    build: ./web  # Указывает на папку 'web' внутри контекста сборки
    volumes:
      - ./data:/app  # Предполагается, что файл vacancies.db находится в папке 'data'
    ports:
      - "8000:8000"
    environment:
      - TOKEN=7255706311:AAEmLmaUnSW0XMdqMGWuHx0FnOJFVfcGF-o